export const mockUser = {
  login: "PrakharJain05",
  id: 65168776,
  node_id: "MDQ6VXNlcjY1MTY4Nzc2",
  avatar_url: "https://avatars1.githubusercontent.com/u/65168776?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/PrakharJain05",
  html_url: "https://github.com/PrakharJain05",
  followers_url: "https://api.github.com/users/PrakharJain05/followers",
  following_url:
    "https://api.github.com/users/PrakharJain05/following{/other_user}",
  gists_url: "https://api.github.com/users/PrakharJain05/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/PrakharJain05/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/PrakharJain05/subscriptions",
  organizations_url: "https://api.github.com/users/PrakharJain05/orgs",
  repos_url: "https://api.github.com/users/PrakharJain05/repos",
  events_url: "https://api.github.com/users/PrakharJain05/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/PrakharJain05/received_events",
  type: "User",
  site_admin: false,
  name: "Prakhar Jain",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: true,
  bio: null,
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2020-05-11T12:00:49Z",
  updated_at: "2020-11-03T13:05:54Z",
};
