export const mockUser = {
  login: "PrakharJain05",
  avatar_url: "https://avatars1.githubusercontent.com/u/65168776?v=4",
  url: "https://api.github.com/users/PrakharJain05",
  html_url: "https://github.com/PrakharJain05",
  followers_url: "https://api.github.com/users/PrakharJain05/followers",
  following_url:
    "https://api.github.com/users/PrakharJain05/following{/other_user}",
  gists_url: "https://api.github.com/users/PrakharJain05/gists{/gist_id}",
  repos_url: "https://api.github.com/users/PrakharJain05/repos",
  name: "Prakhar Jain",
  company: null,
  blog: "",
  location: null,
  bio: null,
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2020-05-11T12:00:49Z",
  updated_at: "2020-11-03T13:05:54Z",
};
